seed: 1234

trainer:
  gpus: 1
  overfit_batches: 0.0
  check_val_every_n_epoch: 2
  fast_dev_run: false
  max_epochs: 2
  min_epochs: 1
  num_sanity_val_steps: 0
  auto_lr_find: false
  checkpoint_callback: true

callbacks:
  model_checkpoint:
    save_top_k: 1
    save_weights_only: true
    mode: "min"
    monitor: "val/loss"
    filename: "{epoch}-{val/loss:.2f}-{val/cer:.2f}"
  early_stopping:
    patience: 3
    mode: "min"
    monitor: "val/loss"
    min_delta: 0.001

data:  # 8
  batch_size: 16
  num_workers: 0
  pin_memory: false

lit_model:
  # Optimizer 0.0003/0.00005
  lr: 0.001
  weight_decay: 0.0001
  # Scheduler
  milestones: [10]
  gamma: 0.5
  # Model
  d_model: 128
  dim_feedforward: 256
  nhead: 4
  dropout: 0.3
  num_decoder_layers: 5
  max_output_len: 400

logger:
  project: "image-to-latex"