[tool.black]
line-length = 120
exclude = '''
/(
      \.eggs
    | \.git
    | \.mypy_cache
    | venv
  )/
'''

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
lines_after_imports = 2
skip_gitignore = true
virtual_env = "venv"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "--strict-markers --disable-pytest-warnings"
markers = [
    "training: tests that involve training",
]